version: "3"
services:
    qbittorrent:
        restart: unless-stopped
        privileged: true
        volumes:
            - /opt/docker/qBittorrent/config/:/config
            - /mnt/plex/:/data
        environment:
            - PUID=0
            - PGID=0
            - TZ=US/Eastern
            - VPN_ENABLED=yes
            - VPN_TYPE=wireguard
            - LAN_NETWORK=10.0.5.0/24
            - ENABLE_SSL=no
            - HEALTH_CHECK_HOST=one.one.one.one
        ports:
            - 8080:8080
        image: dyonr/qbittorrentvpn
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/sonarr:/config
            - /mnt/plex:/data
        ports:
            - 8989:8989
        restart: unless-stopped
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/radarr:/config
            - /mnt/plex:/data
        ports:
            - 7878:7878
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - AUTO_UPDATE=true
        volumes:
            - /opt/pvr/jackett:/config
            - /mnt/plex/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/pvr/overseerr:/config
        ports:
            - 5055:5055
        restart: unless-stopped
